name: "HTML to PDF (supports any js framework)"
description: "Converts an HTML website to a PDF."
branding:
  icon: "file-text"
  color: "gray-dark"
inputs:
  source-path:
    description: "Path to the build (must be a directory)"
    required: true
    default: "build"
  destination-path:
    description: "Where to save the generated PDF (must end with .pdf)"
    required: true
    default: "out.pdf"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --source-path
    - ${{ inputs.source-path }}
    - --destination-path
    - ${{ inputs.destination-path }}
